language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
sudo: false

env:
  global:
  - secure: "KdYU7nWHrw5SdkKqiy/bkephmervpWzEl4YkfIFq6oFi9BJQoT6ty0T81dNXc4c0l9lo4gCaxJlDS2JqINoXiLWDQGKejG1F4l+KrfYz8iZImLlb2byVgAIdC0/vkRZrEtvBFeKTwhR04e+e1NCUcUTt/OImgzhjD025OtRI/MA="

before_install:
  - openssl aes-256-cbc -K $encrypted_9388caed6534_key -iv $encrypted_9388caed6534_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar
  # TODO: Change version number dependent on tag

install:
  # Use nvm to install and select version 0.12 of nodejs instead of the default 0.10
  - nvm install 0.12
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g gulp
  - gem install sass
  - ./install-dependencies.sh

script:
  - gulp build
  - gulp unittest
  #- gulp e2e-tests-headless

  # Either try to build with gradle but without the gradle daemon, works intermittently
  #- gulp build-android-no-gradle-daemon -b
  # Or build with ant, old skool
  - ANDROID_BUILD=ant cordova build --release android
  - mkdir -p builds/android
  - cp platforms/android/bin/MainActivity-release-unsigned.apk builds/android/pottypottypotty-release-unsigned.apk
  # Sign build
  - jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore pottypottypotty-release.keystore builds/android/pottypottypotty-release-unsigned.apk pottypottypotty --storepass $KEY_PASS
  # Zip align build
  - $ANDROID_HOME/build-tools/22.0.1/zipalign 4 builds/android/pottypottypotty-release-unsigned.apk builds/android/pottypottypotty.apk

before_deploy:
  # Install Play store upload dependencies
  - pip install --user PyOpenSSL
  - pip install --user --upgrade google-api-python-client
  # Upload to play store - TODO: Move to deploy script
  - ./upload_to_play_store.py -p com.cjra.pottypottypotty.free -a builds/android/pottypottypotty.apk -s GooglePlayAndroidDeveloper-4d336e73004e.json

deploy:
  provider: releases
  api_key:
    secure: SKYWxcbR6iILEPl+z8kmCNLWz8AvXpvVN4hix6y+ISfMPZQL1lZheE7qEUVbPX4HdHFHcw0d2AyE7AQXYzxBspq2GLTWHZjjn6jakRXGqEiIQytdlUc8ddcuG17IAKvy82SPDRz/9kyIuaPrMIP35fG8LjTFlvxV2EuQCZTqfII=
  file: builds/android/pottypottypotty.apk
  skip_cleanup: true
  on:
    tags: true
    repo: charlesarmitage/PottyPottyPotty
