language: java
before_script:
  # Update Gradle properties first as it seems to restart the build
  - mkdir ~/.gradle
  - cp gradle.properties ~/.gradle

  # Install base Android SDK
  - sudo apt-get update -qq
  # Ensure 32-bit support libs are available if running on 64-bit architecture
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r24.3.3-linux.tgz
  - tar -zxf android-sdk_r24.3.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # only update the sdk for the tools, platform-tools and build-tools (1,2,3) and whatever api level
  # you are building for android (run "android list sdk --all --extended" to get the full list.
  - echo "y" | android update sdk --all --filter tools,platform-tools,build-tools-22.0.1,android-22 --no-ui --force

  # Use nvm to install and select version 0.12 of nodejs instead of the default 0.10
  - nvm install 0.12
  # Install node modules
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g gulp
  - gem install sass
  # Install node modules listed in package.json
  - npm install
  # Install bower modules listed in bower.json
  - bower install
script:
  - gulp build -b
  - cordova platform add android
  - gulp build-android-no-gradle-daemon -b
  - gulp unittest

before_deploy:
  # Deploy apk - todo: add this copy to gulpfile for build-android
  - mkdir -p builds/android
  - cp platforms/android/build/outputs/apk/android-debug.apk builds/android/pottypottypotty-debug.apk

deploy:
  provider: releases
  api_key:
    secure: SKYWxcbR6iILEPl+z8kmCNLWz8AvXpvVN4hix6y+ISfMPZQL1lZheE7qEUVbPX4HdHFHcw0d2AyE7AQXYzxBspq2GLTWHZjjn6jakRXGqEiIQytdlUc8ddcuG17IAKvy82SPDRz/9kyIuaPrMIP35fG8LjTFlvxV2EuQCZTqfII=
  file: builds/android/pottypottypotty-debug.apk
  skip_cleanup: true
  on:
    tags: true
  on:
    repo: charlesarmitage/PottyPottyPotty
