language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
sudo: false

install:
  # Use nvm to install and select version 0.12 of nodejs instead of the default 0.10
  - nvm install 0.12
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g gulp
  - gem install sass
  - npm install
  - bower install
  # TODO: Move to before_deploy once proven that this command works on Travis
  - pip install --user --upgrade google-api-python-client

script:
  - gulp build -b
  - gulp unittest
  - gulp e2e-tests-headless

  - cordova platform add android
  # Either try to build with gradle but without the gradle daemon, works intermittently
  #- gulp build-android-no-gradle-daemon -b
  # Or build with ant, old skool
  - ANDROID_BUILD=ant gulp build-android && mkdir -p platforms/android/build/outputs/apk && cp platforms/android/bin/MainActivity-debug.apk platforms/android/build/outputs/apk/android-debug.apk

before_deploy:
  # Deploy apk - todo: add this copy to gulpfile for build-android (but not if we're doing ant builds!)
  - mkdir -p builds/android
  - cp platforms/android/build/outputs/apk/android-debug.apk builds/android/pottypottypotty-debug.apk

deploy:
  provider: releases
  api_key:
    secure: SKYWxcbR6iILEPl+z8kmCNLWz8AvXpvVN4hix6y+ISfMPZQL1lZheE7qEUVbPX4HdHFHcw0d2AyE7AQXYzxBspq2GLTWHZjjn6jakRXGqEiIQytdlUc8ddcuG17IAKvy82SPDRz/9kyIuaPrMIP35fG8LjTFlvxV2EuQCZTqfII=
  file: builds/android/pottypottypotty-debug.apk
  skip_cleanup: true
  on:
    tags: true
    repo: charlesarmitage/PottyPottyPotty
